import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'

// Register service worker for offline support
async function registerServiceWorker() {
  if ('serviceWorker' in navigator) {
    try {
      // The service worker is auto-generated by vite-plugin-pwa
      const { registerSW } = await import('virtual:pwa-register')
      
      const updateSW = registerSW({
        onNeedRefresh() {
          // Show a prompt to the user when a new version is available
          if (confirm('New content available. Reload to update?')) {
            updateSW(true)
          }
        },
        onOfflineReady() {
          console.log('App ready for offline use')
        },
        onRegistered(registration) {
          console.log('Service Worker registered:', registration)
          
          // Check for updates periodically (every hour)
          setInterval(() => {
            registration?.update()
          }, 60 * 60 * 1000)
        },
        onRegisterError(error) {
          console.error('Service Worker registration failed:', error)
        }
      })
    } catch (error) {
      console.error('Failed to register service worker:', error)
    }
  }
}

// Initialize the app
createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)

// Register service worker after app loads
registerServiceWorker()
